set(_CATKIN_CURRENT_PACKAGE "no_enemy_app")
set(no_enemy_app_VERSION "0.0.0")
set(no_enemy_app_MAINTAINER "robot <robot@todo.todo>")
set(no_enemy_app_PACKAGE_FORMAT "2")
set(no_enemy_app_BUILD_DEPENDS "actionlib" "cv_bridge" "libpcl-all" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "waterplus_map_tools" "wpb_home_behaviors" "wpb_home_tutorials" "xfyun_waterplus" "other_catkin_pkg")
set(no_enemy_app_BUILD_EXPORT_DEPENDS "actionlib" "cv_bridge" "libpcl-all" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "waterplus_map_tools" "wpb_home_behaviors" "wpb_home_tutorials" "xfyun_waterplus" "other_catkin_pkg")
set(no_enemy_app_BUILDTOOL_DEPENDS "catkin")
set(no_enemy_app_BUILDTOOL_EXPORT_DEPENDS )
set(no_enemy_app_EXEC_DEPENDS "actionlib" "cv_bridge" "libpcl-all" "message_runtime" "message_runtime" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "waterplus_map_tools" "wpb_home_behaviors" "wpb_home_tutorials" "xfyun_waterplus" "other_catkin_pkg")
set(no_enemy_app_RUN_DEPENDS "actionlib" "cv_bridge" "libpcl-all" "message_runtime" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf" "visualization_msgs" "waterplus_map_tools" "wpb_home_behaviors" "wpb_home_tutorials" "xfyun_waterplus" "other_catkin_pkg")
set(no_enemy_app_TEST_DEPENDS )
set(no_enemy_app_DOC_DEPENDS )
set(no_enemy_app_URL_WEBSITE "")
set(no_enemy_app_URL_BUGTRACKER "")
set(no_enemy_app_URL_REPOSITORY "")
set(no_enemy_app_DEPRECATED "")