port: /dev/dashgo
#port: /dev/port1
baud: 115200
timeout: 0.1
rate: 50
sensorstate_rate: 10

useImu: True
useSonar: False
use_base_controller: True
base_controller_rate: 10

sonar_height: 0.15
sonar_safe_distance: 8
sonar_dec_distance: 40.0  ##decelerate

sonar0_offset_yaw: -3.14
sonar0_offset_x: -0.1
sonar0_offset_y: -0.04

sonar1_offset_yaw: -0.87  #-50 du
sonar1_offset_x: 0.24
sonar1_offset_y: -0.08

sonar2_offset_yaw: 0.0
sonar2_offset_x: 0.24
sonar2_offset_y: 0.0

sonar3_offset_yaw: 0.87 #50 du
sonar3_offset_x: 0.24
sonar3_offset_y: 0.08

sonar4_offset_yaw: 3.14
sonar4_offset_x: -0.1
sonar4_offset_y: 0.04

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.1280
wheel_track: 0.3559
encoder_resolution: 1200
gear_reduction: 1.0
motors_reversed: False

# === PID parameters
Kp: 50
Kd: 20
Ki: 0
Ko: 50
accel_limit: 1.0
