#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/robot/batkin/devel_isolated/cartographer_ros:/home/robot/batkin/devel_isolated/cartographer_ros_msgs:/home/robot/batkin/devel_isolated/camera_calibration:/home/robot/batkin/devel_isolated/autolabor_test_launch:/home/robot/batkin/devel_isolated/autolabor_simulation_object:/home/robot/batkin/devel_isolated/autolabor_simulation_stage:/home/robot/batkin/devel_isolated/autolabor_simulation_location:/home/robot/batkin/devel_isolated/autolabor_simulation_lidar:/home/robot/batkin/devel_isolated/autolabor_simulation_base:/home/robot/batkin/devel_isolated/autolabor_navigation_launch:/home/robot/batkin/devel_isolated/autolabor_keyboard_control:/home/robot/batkin/devel_isolated/autolabor_description:/home/robot/batkin/devel_isolated/ah100b:/home/robot/catkin_ws/devel:/opt/ros/kinetic:/home/robot/batkin/devel_isolated/cartographer:/home/robot/batkin/devel_isolated/ceres-solver:/home/robot/batkin/devel_isolated/cartographer:/home/robot/batkin/devel_isolated/ceres-solver'
export LD_LIBRARY_PATH='/home/robot/batkin/devel_isolated/cartographer_ros/lib:/home/robot/batkin/devel_isolated/cartographer_ros_msgs/lib:/home/robot/batkin/devel_isolated/camera_calibration/lib:/home/robot/batkin/devel_isolated/autolabor_test_launch/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_object/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_stage/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_location/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_lidar/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_base/lib:/home/robot/batkin/devel_isolated/autolabor_navigation_launch/lib:/home/robot/batkin/devel_isolated/autolabor_keyboard_control/lib:/home/robot/batkin/devel_isolated/autolabor_description/lib:/home/robot/batkin/devel_isolated/ah100b/lib:/home/robot/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/robot/batkin/devel_isolated/cartographer/lib:/home/robot/batkin/devel_isolated/cartographer/lib/x86_64-linux-gnu:/home/robot/batkin/devel_isolated/ceres-solver/lib:/home/robot/batkin/devel_isolated/ceres-solver/lib/x86_64-linux-gnu:/home/robot/batkin/devel_isolated/cartographer/lib:/home/robot/batkin/devel_isolated/ceres-solver/lib'
export PATH='/opt/ros/kinetic/bin:/home/robot/batkin/devel_isolated/cartographer/bin:/home/robot/batkin/devel_isolated/ceres-solver/bin:/home/robot/batkin/devel_isolated/cartographer/bin:/home/robot/bin:/home/robot/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/robot/batkin/devel_isolated/cartographer_ros/lib/pkgconfig:/home/robot/batkin/devel_isolated/cartographer_ros_msgs/lib/pkgconfig:/home/robot/batkin/devel_isolated/camera_calibration/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_test_launch/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_simulation_object/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_simulation_stage/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_simulation_location/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_simulation_lidar/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_simulation_base/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_navigation_launch/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_keyboard_control/lib/pkgconfig:/home/robot/batkin/devel_isolated/autolabor_description/lib/pkgconfig:/home/robot/batkin/devel_isolated/ah100b/lib/pkgconfig:/home/robot/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig:/home/robot/batkin/devel_isolated/cartographer/lib/pkgconfig:/home/robot/batkin/devel_isolated/cartographer/lib/x86_64-linux-gnu/pkgconfig:/home/robot/batkin/devel_isolated/ceres-solver/lib/pkgconfig:/home/robot/batkin/devel_isolated/ceres-solver/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/robot/batkin/devel_isolated/cartographer_ros_msgs/lib/python2.7/dist-packages:/home/robot/batkin/devel_isolated/camera_calibration/lib/python2.7/dist-packages:/home/robot/batkin/devel_isolated/autolabor_simulation_stage/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/home/robot/batkin/devel_isolated/cartographer/lib/python2.7/dist-packages:/home/robot/batkin/devel_isolated/ceres-solver/lib/python2.7/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/robot/batkin/devel_isolated/cartographer_ros/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/robot/batkin/src/mapping/cartographer_ros/cartographer_ros:$ROS_PACKAGE_PATH"