set(_CATKIN_CURRENT_PACKAGE "stim")
set(stim_VERSION "0.0.0")
set(stim_MAINTAINER "wesker <wesker@todo.todo>")
set(stim_PACKAGE_FORMAT "2")
set(stim_BUILD_DEPENDS "roscpp" "std_msgs")
set(stim_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(stim_BUILDTOOL_DEPENDS "catkin")
set(stim_BUILDTOOL_EXPORT_DEPENDS )
set(stim_EXEC_DEPENDS "roscpp" "std_msgs")
set(stim_RUN_DEPENDS "roscpp" "std_msgs")
set(stim_TEST_DEPENDS )
set(stim_DOC_DEPENDS )
set(stim_URL_WEBSITE "")
set(stim_URL_BUGTRACKER "")
set(stim_URL_REPOSITORY "")
set(stim_DEPRECATED "")