#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/robot/batkin/devel_isolated/lego_loam:/home/robot/batkin/devel_isolated/joy_to_twist:/home/robot/batkin/devel_isolated/image_view:/home/robot/batkin/devel_isolated/image_rotate:/home/robot/batkin/devel_isolated/image_publisher:/home/robot/batkin/devel_isolated/image_proc:/home/robot/batkin/devel_isolated/image_pipeline:/home/robot/batkin/devel_isolated/fake_localization:/home/robot/batkin/devel_isolated/depth_image_proc:/home/robot/batkin/devel_isolated/dashgo_driver:/home/robot/batkin/devel_isolated/cloud_msgs:/home/robot/batkin/devel_isolated/cartographer_rviz:/home/robot/batkin/devel_isolated/cartographer_ros:/home/robot/batkin/devel_isolated/cartographer_ros_msgs:/home/robot/batkin/devel_isolated/camera_calibration:/home/robot/batkin/devel_isolated/autolabor_test_launch:/home/robot/batkin/devel_isolated/autolabor_simulation_object:/home/robot/batkin/devel_isolated/autolabor_simulation_stage:/home/robot/batkin/devel_isolated/autolabor_simulation_location:/home/robot/batkin/devel_isolated/autolabor_simulation_lidar:/home/robot/batkin/devel_isolated/autolabor_simulation_base:/home/robot/batkin/devel_isolated/autolabor_navigation_launch:/home/robot/batkin/devel_isolated/autolabor_keyboard_control:/home/robot/batkin/devel_isolated/autolabor_description:/opt/ros/kinetic:/home/robot/batkin/devel_isolated/cartographer:/home/robot/batkin/devel_isolated/ceres-solver'
export LD_LIBRARY_PATH='/home/robot/batkin/devel_isolated/lego_loam/lib:/home/robot/batkin/devel_isolated/joy_to_twist/lib:/home/robot/batkin/devel_isolated/image_view/lib:/home/robot/batkin/devel_isolated/image_rotate/lib:/home/robot/batkin/devel_isolated/image_publisher/lib:/home/robot/batkin/devel_isolated/image_proc/lib:/home/robot/batkin/devel_isolated/fake_localization/lib:/home/robot/batkin/devel_isolated/depth_image_proc/lib:/home/robot/batkin/devel_isolated/dashgo_driver/lib:/home/robot/batkin/devel_isolated/cloud_msgs/lib:/home/robot/batkin/devel_isolated/cartographer_rviz/lib:/home/robot/batkin/devel_isolated/cartographer_ros/lib:/home/robot/batkin/devel_isolated/cartographer_ros_msgs/lib:/home/robot/batkin/devel_isolated/camera_calibration/lib:/home/robot/batkin/devel_isolated/autolabor_test_launch/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_object/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_stage/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_location/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_lidar/lib:/home/robot/batkin/devel_isolated/autolabor_simulation_base/lib:/home/robot/batkin/devel_isolated/autolabor_navigation_launch/lib:/home/robot/batkin/devel_isolated/autolabor_keyboard_control/lib:/home/robot/batkin/devel_isolated/autolabor_description/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/robot/batkin/devel_isolated/cartographer/lib:/home/robot/batkin/devel_isolated/ceres-solver/lib'
export PATH='/opt/ros/kinetic/bin:/home/robot/batkin/devel_isolated/cartographer/bin:/home/robot/bin:/home/robot/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH="/home/robot/batkin/devel_isolated/lego_loam/lib/pkgconfig:$PKG_CONFIG_PATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/robot/batkin/devel_isolated/lego_loam/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/robot/batkin/src/LeGO-LOAM_NOTED-master/src/LeGO-LOAM:$ROS_PACKAGE_PATH"